USE ARCODE
CREATE DATABASE GravadoraSQL
USE GravadoraSQL

CREATE TABLE Autor
(

    COD_AUTOR INT PRIMARY KEY IDENTITY,
    NOME_AUTOR VARCHAR(100)
);
GO

CREATE TABLE GRAVADORA
(
    COD_GRAVADORA INT PRIMARY KEY IDENTITY,
    NOME_GRAVADORA VARCHAR(50) NOT NULL,
    ENDERECO_GRAVADORA VARCHAR(50) NOT NULL,
    TELEFONE_GRAVADORA VARCHAR(12) NOT NULL,
    CONTATO VARCHAR(10),
    URL VARCHAR(100)
);
GO

CREATE TABLE MUSICA
(
    CODIGO_MUSICA INT PRIMARY KEY IDENTITY,
    NOME_MUSICA VARCHAR(25) NOT NULL,
    NUMERO_FAIXA NUMERIC 
);

CREATE TABLE CD
(
    COD_CD INT PRIMARY KEY IDENTITY,
    NOME_CD VARCHAR(25) NOT NULL,
    COD_GRAVADORA INT FOREIGN KEY REFERENCES GRAVADORA(COD_GRAVADORA),
    PRECO DECIMAL,
    TEMPO_TOTAL FLOAT,
    CD_INDICADO INT
);

CREATE TABLE ITEM_CD
(
    COD_CD INT FOREIGN KEY REFERENCES CD(COD_CD),
    NUM_FAIXA NUMERIC,
    CODIGO_MUSICA INT FOREIGN KEY REFERENCES MUSICA(CODIGO_MUSICA)
);

CREATE TABLE MUSICA_AUTOR
(
    COD_MUSICA INT FOREIGN KEY REFERENCES MUSICA(CODIGO_MUSICA),
    COD_AUTOR INT FOREIGN KEY REFERENCES AUTOR(COD_AUTOR)
);

SELECT * FROM Autor
SELECT * FROM GRAVADORA
SELECT * FROM MUSICA
SELECT * FROM CD
SELECT * FROM ITEM_CD
SELECT * FROM MUSICA_AUTOR
