USE ARCODE
CREATE DATABASE GravadoraSQL
USE GravadoraSQL

CREATE TABLE Autor
(

    COD_AUTOR INT PRIMARY KEY IDENTITY,
    NOME_AUTOR VARCHAR(100)
);
GO

CREATE TABLE GRAVADORA
(
    COD_GRAVADORA INT PRIMARY KEY IDENTITY,
    NOME_GRAVADORA VARCHAR(50) NOT NULL,
    ENDERECO_GRAVADORA VARCHAR(50) NOT NULL,
    TELEFONE_GRAVADORA VARCHAR(12) NOT NULL,
    CONTATO VARCHAR(10),
    URL VARCHAR(100)
);
GO


SELECT * FROM Autor, GRAVADORA
